### ISSUE TITLE
The lib analytics in Databricks not delivery 100% of calls

### ISSUE THREAD

**Issue by gevored** [segmentio/analytics-python#243] opened 2022-11-30 15:12 UTC
Hello

I am trying to iterate from a table using python in Databricks and send a identify and track call to a python source in Segment, but I noticed is not every rows/calls that arrive in segment, I didn't receive any erro when I execute  analytics.identify() or nalytics.track(), only a message on console "analytics-python queue is full" . 

in my tests the volume of data is 50k of rows with 8 columns (properties)

only 37k is arriving in Segment
flow rate: 5.8k/min

our goal is send around 10 MM of calls by day from our data lake

My questions :
1) Is there a way to garantee which every calls arrive in Segment ?
2) Is there a way to increase the flow rate ?

Thanks

**Comment by nd4p90x** [comment] 2022-11-30 15:22
Is this in a prod env or are you using the debugger in app.segment.com?

**Comment by gevored** [comment] 2022-11-30 15:39
prod env, I am using this lib to send calls directly to Segment

**Comment by nd4p90x** [comment] 2022-11-30 15:41
Thank you for that clarification.   Let us review and get back with you shortly.

**Comment by nd4p90x** [comment] 2022-11-30 21:13
@gevored Without asking for other specific info, I can only assume that you are looking at the segment debugger to validate the messages you are sending?  If this is the case, the debugger by design does not record every single entry sent to it.
![Screen Shot 2022-11-30 at 3 12 09 PM](https://user-images.githubusercontent.com/2658588/204909235-dee4cb15-bd3d-4444-ae9e-eacbda986fc1.png)

**Comment by gevored** [comment] 2022-12-02 12:38
Yeah the  Debbuger have just a sample of the data,but actually I compared through the Schema data source tab, before starting and after finishing
<img width="785" alt="image" src="https://user-images.githubusercontent.com/14332784/205294026-bc676957-1375-4cf0-92c4-292ac8ba3102.png">

in parallel I am using a http post and this solution is delivering 100% of the calls, but I expected this python lib  solution to have a better result

**Comment by nd4p90x** [comment] 2022-12-13 22:32
@gevored Can you enable logging and verify the records that are being sent are accurate and let us know the results?
https://segment.com/docs/connections/sources/catalog/libraries/server/python/#logging

Thank you,

**Comment by MichaelGHSeg** [comment] 2023-01-25 18:51
Closing this issue.  Please reopen if you keep seeing this behavior, we would like to get some logs to understand the issue.

**Closed by MichaelGHSeg** 2023-01-25 18:51 UTC
